{{/*
Create a name for apiProxy
We truncate at 54 chars in order to provide space for the "-api-proxy" suffix
*/}}
{{- define "zaakbrug.apiProxyName" -}}
{{ include "ff-common.name" . | trunc 54 | trimSuffix "-" }}-api-proxy
{{- end }}

{{/*
Create a default fully qualified name for apiProxy.
We truncate at 54 chars in order to provide space for the "-api-proxy" suffix
*/}}
{{- define "zaakbrug.apiProxyFullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.staging.apiProxy.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default "api-proxy" .Values.staging.apiProxy.nameOverride }}
{{- if contains $name (include "ff-common.fullname" .) }}
{{- include "ff-common.fullname" . | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" (include "ff-common.fullname" .) $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end -}}

{{/*
apiProxy labels
*/}}
{{- define "zaakbrug.apiProxyLabels" -}}
helm.sh/chart: {{ include "ff-common.chart" . }}
{{ include "zaakbrug.apiProxySelectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
apiProxy selector labels
*/}}
{{- define "zaakbrug.apiProxySelectorLabels" -}}
app.kubernetes.io/name: {{ include "zaakbrug.apiProxyName" . }}
{{- end }}
