{{- if .Values.zaakbrug.profiles -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ff-common.fullname" . }}-profiles
  labels:
    {{- include "ff-common.labels" . | nindent 4 }}
data:
  Profiles.json: |-
   {{ .Values.zaakbrug.profiles | toJson }}
{{- end -}}
