apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "zaakbrug.fullname" . }}-env
  labels:
    {{- include "zaakbrug.labels" . | nindent 4 }}
data:
  zaakbrug.zds.timezone: "{{ .Values.zaakbrug.zds.timezone | default "UTC" }}"