{{- template "ff-common.configmap.env" (list . "zaakbrug.configmap.env") -}}
{{- define "zaakbrug.configmap.env" -}}
data:
  zaakbrug.zds.timezone: "{{ .Values.zaakbrug.zds.timezone | default "UTC" }}"
{{- end -}}