{{- if .Values.staging.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zaakbrug.apiProxyFullname" . }}
  labels:
    {{- include "zaakbrug.apiProxyLabels" . | nindent 4 }}
  {{- with .Values.staging.apiProxy.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }} : {{ tpl ($value | toString) $ }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.staging.apiProxy.service.type }}
  ports:
    - port: {{ .Values.staging.apiProxy.service.port }}
      targetPort: 8080
      name: http
  selector:
    {{- include "zaakbrug.apiProxySelectorLabels" . | nindent 4 }}
{{- end -}}