{{/*
ConfigMap for generating override.conf files
*/}}
{{- if (not .Values.drill.overrideConfiguration.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drill.fullname" . }}-override
  labels:
    {{- include "drill.labels" . | nindent 4 }}
data:
  drill-override.conf: |-
    drill.exec: {
      cluster-id: "{{ include "drill.fullname" . }}",
      zk.connect: "{{ include "zookeeper.fullname" . }}:2181",
      http.port: 8047
    }
    {{- toString .Values.drill.overrideConfiguration.drill | nindent 4 }}
  {{- with .Values.drill.overrideConfiguration.drillMetastore }}
  drill-metastore-override.conf: |-
    {{- toString . | nindent 4 }}
  {{- end }}
  {{- with .Values.drill.overrideConfiguration.drillOnYarn}}
  drill-on-yarn.conf: |-
    {{- toString . | nindent 4 }}
  {{- end }}
  {{- with .Values.drill.overrideConfiguration.drillSqlLine }}
  drill-sqlline-override.conf: |-
    {{- toString . | nindent 4 }}
  {{- end }}
  {{- with .Values.drill.overrideConfiguration.storagePlugins }}
  storage-plugins-override.conf: |-
    {{- toString . | nindent 4 }}
  {{- end }}
  logback.xml: |-
    <configuration>
      <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>/var/lib/drill/log/drill.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <fileNamePattern>/var/lib/drill/log/drill.%i.log</fileNamePattern>
            <minIndex>1</minIndex>
            <maxIndex>9</maxIndex>
        </rollingPolicy>

        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
            <maxFileSize>5MB</maxFileSize>
        </triggeringPolicy>

        <encoder>
            <pattern>%date [%thread] %-5level %logger{35} - %msg%n</pattern>
        </encoder>
      </appender>

      <root level="debug">
          <appender-ref ref="FILE"/>
      </root>

      <logger name="org.apache.drill" level="trace"/>
      <logger name="org.apache.calcite" level="trace"/>
      <logger name="org.apache.zookeeper" level="trace"/>
    </configuration>
{{- end -}}