{{/*
ConfigMap for generating override.conf files
*/}}
{{- if (not .Values.drill.overrideConfiguration.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drill.fullname" . }}-override
  labels:
    {{- include "drill.labels" . | nindent 4 }}
data:
  drill-override.conf: |-
    drill.exec: {
      cluster-id: "{{ include "drill.fullname" . }}",
      zk.connect: "{{ include "zookeeper.fullname" . }}:2181",
      http.port: 8047
    }
    {{- toString .Values.drill.overrideConfiguration.drill | nindent 4 }}
  {{- with .Values.drill.overrideConfiguration.drillMetastore }}
  drill-metastore-override.conf: |-
    {{- toString . | nindent 4 }}
  {{- end }}
  {{- with .Values.drill.overrideConfiguration.drillOnYarn}}
  drill-on-yarn.conf: |-
    {{- toString . | nindent 4 }}
  {{- end }}
  {{- with .Values.drill.overrideConfiguration.drillSqlLine }}
  drill-sqlline-override.conf: |-
    {{- toString . | nindent 4 }}
  {{- end }}
  {{- with .Values.drill.overrideConfiguration.storagePlugins }}
  storage-plugins-override.conf: |-
    {{- toString . | nindent 4 }}
  {{- end }}
{{- end -}}