apiVersion: apps/v1
kind: StatefulSet
{{ template "drill.metadata" . }}
spec:
  serviceName: {{ include "drill.fullname" . }}
  podManagementPolicy: Parallel
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "drill.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drill.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
     {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - drill-app
              topologyKey: "kubernetes.io/hostname"
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drill.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.registry }}{{ if .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          stdin: true
          command:
            - /bin/bash
            - -c
            - "${DRILL_HOME}/bin/drillbit.sh start && tail -f /var/lib/drill/log/drillbit.out"
          ports:
            - containerPort: 8047
              name: web
            - containerPort: 31010
              name: user
            - containerPort: 31011
              name: control
            - containerPort: 31012
              name: data
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
            exec:
              command:
                - /bin/bash
                - -c
                - "${DRILL_HOME}/bin/drillbit.sh status"
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
            exec:
              command:
                  - /bin/bash
                  - -c
                  - "${DRILL_HOME}/bin/drillbit.sh status"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
            exec:
              command:
                - /bin/bash
                - -c
                - "${DRILL_HOME}/bin/drillbit.sh status"
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - "if [ \"$(id -u)\" -ne 0 ]; then ${DRILL_HOME}/bin/drillbit.sh stop; else ${DRILL_HOME}/bin/drillbit.sh graceful_stop; fi"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /opt/drill/conf/
              name: {{ template "drill.fullname" . }}-override
            - mountPath: /etc/passwd
              name: {{ template "drill.fullname" . }}-users
              subPath: passwd
            - name: {{ template "drill.fullname" . }}-logs
              mountPath: /var/lib/drill/log
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
        - name: {{ template "drill.fullname" . }}-override
          configMap:
            {{- if .Values.drill.overrideConfiguration.existingConfigMap }}
            name: {{ .Values.drill.overrideConfiguration.existingConfigMap }}
            {{- else }}
            name: {{ template "drill.fullname" . }}-override
            {{- end }}
        - name: {{ template "drill.fullname" . }}-users
          secret:
            {{- if .Values.drill.authentication.existingSecret }}
            secretName: {{ .Values.drill.authentication.existingSecret }}
            {{- else }}
            secretName: {{ template "drill.fullname" . }}-users
            {{- end }}
        {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        -  name: {{ template "drill.fullname" . }}-logs
           persistentVolumeClaim:
             claimName: {{ .Values.persistence.existingClaim }}
        {{- else if (not .Values.persistence.enabled) }}
        - name: {{ template "drill.fullname" . }}-logs
          emptyDir: {}
        {{- end }}
      initContainers:
        - name: zookeeper-available
          image: busybox
          command: [ 'sh', '-c', 'until nc -z {{ include "zookeeper.fullname" . }} 2181; do echo Waiting for ZooKeeper to come up; sleep 5; done; ' ]
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: {{ template "drill.fullname" . }}-logs
        labels:
          {{- include "drill.labels" . | nindent 10 }}
        {{- if .Values.persistence.annotations }}
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        selector:
          {{- toYaml .Values.persistence.selector | nindent 10 }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}

