apiVersion: v2
appVersion: 1.13.7
description: A Helm chart for running ZaakBrug on Kubernetes
name: zaakbrug
icon: https://raw.githubusercontent.com/wearefrank/charts/master/charts/zaakbrug/icon.png
type: application
version: 2.0.17

dependencies:
- name: ff-common
  version: ~0.1.17
  repository: https://frankframework.github.io/charts/
- name: openzaak
  alias: staging
  version: 1.1.1
  repository: https://maykinmedia.github.io/charts/
  condition: staging.enabled
